# Generated by Django 3.1.3 on 2020-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('particularidade', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
    ]
